# Generated by Django 2.1.2 on 2018-11-07 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talker', models.CharField(max_length=40)),
                ('message', models.CharField(blank=True, max_length=40)),
            ],
        ),
    ]
