# Generated by Django 2.1.1 on 2018-10-05 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tm',
            name='message',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='tm',
            name='talker',
            field=models.CharField(max_length=40),
        ),
    ]
